"""Protocol for billing_service HTTP client. Real: BillingServiceClient; stub: StubBillingServiceClient."""

from typing import Any, Protocol


class BillingServiceClientProtocol(Protocol):
    """Interface for billing_service client (plans, orders, subscriptions)."""

    async def list_plans(self) -> list[dict[str, Any]]: ...

    async def get_plan(self, plan_id: str) -> dict[str, Any]: ...

    async def create_plan(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def update_plan(self, plan_id: str, data: dict[str, Any]) -> dict[str, Any]: ...

    async def create_order(self, user_id: str, plan_id: str) -> dict[str, Any]: ...

    async def get_order(self, order_id: str) -> dict[str, Any]: ...

    async def list_orders_by_user(self, user_id: str) -> list[dict[str, Any]]: ...

    async def list_orders(
        self,
        offset: int = 0,
        limit: int = 50,
        status: str | None = None,
    ) -> dict[str, Any]: ...

    async def get_active_subscription(self, user_id: str) -> dict[str, Any] | None: ...

    async def get_subscription(self, subscription_id: str) -> dict[str, Any]: ...

    async def list_subscriptions(
        self,
        offset: int = 0,
        limit: int = 50,
        status: str | None = None,
    ) -> dict[str, Any]: ...

    async def extend_subscription(self, subscription_id: str, days: int) -> dict[str, Any]: ...

    async def revoke_subscription(self, subscription_id: str) -> dict[str, Any]: ...

    async def close(self) -> None: ...
